### ISSUE TITLE
question about shape-biased network

### ISSUE THREAD

**Issue by rgeirhos** [Chenglin-Yang/PatchAttack#1]
Hey there, sorry for posting an issue, I didn't find an Email address in your paper.
Quick question: when you refer to a "shape-biased network", which network are you referring to?
(https://github.com/rgeirhos/texture-vs-shape/blob/master/models/load_pretrained_models.py lists three different ResNet's with different degrees of stylized training)

**Comment by Chenglin-Yang** [comment]
Hi, thank you for you interest in our paper. The code is just released. In our paper, we report the attacking results of 'Shape-Network' which is model_C in this [script](https://github.com/rgeirhos/texture-vs-shape/blob/master/models/load_pretrained_models.py). We attacked model_A and model_B before, and it showed that they can also be attacked.

**Comment by rgeirhos** [comment]
Thanks for your reply. Since model_C is fine-tuned on ImageNet it is fairly similar to a standard ImageNet-trained ResNet, thus model_A or model_B would have been a more interesting test case in my opinion.
